CREATE TABLE soketType(
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE CPU(
	_id SERIAL PRIMARY KEY NOT NULL,
	vid INTEGER NOT NULL,
	vendor VARCHAR(255) NOT NULL,
	pid INTEGER NOT NULL,
	_name VARCHAR(255) NOT NULL,
	_soketType INTEGER NOT NULL,
	frequency BIGINT NOT NULL,
	coreCount INTEGER NOT NULL,
	hyperThreading BOOLEAN NOT NULL,
	l1CacheCapacity INTEGER NOT NULL,
	l2CacheCapacity INTEGER NOT NULL,
	l3CacheCapacity INTEGER NOT NULL,
	FOREIGN KEY (_soketType) REFERENCES soketType(_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE RamType (
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE RamFormFactor (
 	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE RAM (
	_id SERIAL PRIMARY KEY NOT NULL,
	vid INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	vendor VARCHAR(255) NOT NULL,
	capacity BIGINT NOT NULL,
	_rank INTEGER NOT NULL,
	frequency BIGINT NOT NULL,
	_ramType INTEGER NOT NULL,
	_ramFormFactor INTEGER NOT NULL,
	FOREIGN KEY (_ramType) REFERENCES RamType(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (_ramFormFactor) REFERENCES RamFormFactor(_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE PCInterfaces (
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE FormFactorHdd (
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE Hdd
(
	_id SERIAL PRIMARY KEY NOT NULL,
	vid INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	vendor VARCHAR(255) NOT NULL,
	capacity BIGINT NOT NULL,
	interface_ INTEGER NOT NULL,
	linearSpeedOfWrite BIGINT NOT NULL,
	linearSpeedOfRead BIGINT NOT NULL,
	randomSpeedOfWrite BIGINT NOT NULL,
	randomSpeedOfRead BIGINT NOT NULL,
	FOREIGN KEY (interface_) REFERENCES PCInterfaces(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	
	_rotationSpeed INTEGER NOT NULL,
	_formFactorHdd INTEGER NOT NULL,
	FOREIGN KEY (_formFactorHdd) REFERENCES FormFactorHdd(_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE MemoryTypeSsd (
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE FormFactorSsd (
	_id SERIAL PRIMARY KEY NOT NULL,
	_name VARCHAR(255) NOT NULL
);
CREATE TABLE Ssd
(
	_id SERIAL PRIMARY KEY NOT NULL,
	vid INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	vendor VARCHAR(255) NOT NULL,
	capacity BIGINT NOT NULL,
	interface_ INTEGER NOT NULL,
	linearSpeedOfWrite BIGINT NOT NULL,
	linearSpeedOfRead BIGINT NOT NULL,
	randomSpeedOfWrite BIGINT NOT NULL,
	randomSpeedOfRead BIGINT NOT NULL,
	FOREIGN KEY (interface_) REFERENCES PCInterfaces(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	
	_memoryTypeSsd INTEGER NOT NULL,
	_formFactorSsd INTEGER NOT NULL,
	FOREIGN KEY (_memoryTypeSsd) REFERENCES memoryTypeSsd(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (_formFactorSsd) REFERENCES formFactorSsd(_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Motherboard(
	_id SERIAL PRIMARY KEY NOT NULL,
	vid INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	vendor VARCHAR(255) NOT NULL,
	_cpu INTEGER NULL,
	FOREIGN KEY (_cpu) REFERENCES Cpu(_id) ON DELETE SET NULL ON UPDATE CASCADE
	
);
CREATE TABLE HddLists(
	_id SERIAL PRIMARY KEY NOT NULL,
	motherboard INTEGER NOT NULL,
	_hdd INTEGER NOT NULL,
	FOREIGN KEY (motherboard) REFERENCES Motherboard(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (_hdd) REFERENCES Hdd(_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE SsdLists(
	_id SERIAL PRIMARY KEY NOT NULL,
	motherboard INTEGER NOT NULL,
	_ssd INTEGER NOT NULL,
	FOREIGN KEY (motherboard) REFERENCES Motherboard(_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (_ssd) REFERENCES Ssd(_id) ON DELETE SET NULL ON UPDATE CASCADE
);